# Generated by Django 2.2.1 on 2019-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('venue', models.TextField()),
                ('poster_img', models.URLField()),
                ('thumbnail_img', models.URLField()),
                ('n_rounds', models.IntegerField(blank=True)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('instructions', models.TextField()),
            ],
        ),
    ]
